ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**/*
          - codecov.yml
          - .coderabbit.yml

config:
  - changed-files:
      - any-glob-to-any-file:
          - deno.json
          - deno.lock
          - .demmithub.yml
          - .gitignore
          - src/utils/config.ts
          - src/constants/config.ts

commands:
  - changed-files:
      - any-glob-to-any-file:
          - src/commands/**/*
          - src/lib/command.ts

components:
  - changed-files:
      - any-glob-to-any-file:
          - src/components/**/*

constants:
  - changed-files:
      - any-glob-to-any-file:
          - src/constants/**/*

services:
  - changed-files:
      - any-glob-to-any-file:
          - src/services/**/*

issue:
  - changed-files:
      - any-glob-to-any-file:
          - src/features/issue/**/*
          - src/services/github/issue.ts

commit:
  - changed-files:
      - any-glob-to-any-file:
          - src/features/commit/**/*
          - src/services/git/**/*

utils:
  - changed-files:
      - any-glob-to-any-file:
          - src/utils/**/*
          - src/type.ts
          - src/schema.ts

core:
  - changed-files:
      - any-glob-to-any-file:
          - src/demmithub.ts
          - src/main.ts

test:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*_test.ts"
