comment:
  layout: "header, diff, changes"
  require_changes: false
  after_n_builds: 1

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 0%
