export const LANGUAGE = [
  "en - English",
  "ja - 日本語 (Japanese)",
  "zh - 中文 (Chinese)",
  "ko - 한국어 (Korean)",
  "es - Español (Spanish)",
  "fr - Français (French)",
  "de - Deutsch (German)",
  "it - Italiano (Italian)",
  "pt - Português (Portuguese)",
  "ru - Русский (Russian)",
  "ar - العربية (Arabic)",
  "hi - हिन्दी (Hindi)",
  "tr - Türkçe (Turkish)",
  "vi - Tiếng Việt (Vietnamese)",
  "th - ไทย (Thai)",
];
